import type { Metadata } from "next";
import { Geom } from "next/font/google";
import "./globals.css";

const geom = Geom({
  variable: "--font-geom",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geom.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
